[package]
name = "binbasebackend_engine_native"
version = "0.1.0"
authors = []

[lib]
name = "binbasebackend_engine_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.20.0"
rustler_codegen = "0.20.0"
lazy_static = "1.0"
rand = "0.6.0"