# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

#orbs:
#  heroku: circleci/heroku@0.0.5
#  codecov: codecov/codecov@1.0.4
  
workflows:
  version: 2
  main:
    jobs:
      - build_test
#      - heroku_deploy:
#          requires:
#            - build_test
jobs:
#  heroku_deploy:
#    executor: heroku/default
#    steps:
#      - checkout
#      - heroku/install
#      - heroku/deploy-via-git:
#          app-name: "binbasewallet"
  build_test:
    parallelism: 4
    docker:
      # specify the version you desire here
      - image: dsslimshaddy/binbase_backend
        environment:  # environment variables for primary container
          MIX_ENV: test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:latest
         #environment:  # environment variables for database
          #POSTGRES_USER: postgres
          #POSTGRES_DB: app_test
          #POSTGRES_PASSWORD:
      - image: rabbitmq:latest
        environment:
          RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
          RABBITMQ_DEFAULT_USER: "rabbitmq"
          RABBITMQ_DEFAULT_PASS: "rabbitmq"
          RABBITMQ_DEFAULT_VHOST: "/"
    working_directory: ~/app

    steps:  # commands that comprise the `build` job
      - checkout  # check out source code to working directory

      - run:  # special utility that stalls main process until DB is ready
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # run tests!
      - run: mix test
#      - codecov/upload:
#          file: coverage/*.json